name: arkademi_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  percent_indicator: 4.2.2
  contained_tab_bar_view: 0.8.0
  http: 0.13.4
  flutter_downloader: 1.8.1
  path_provider: 2.0.11
  open_file: 3.2.1
  file_picker: 4.6.1
  dio: 4.0.6
  video_player: any
  html: 0.15.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

